CREATE TABLE Appointments (
    AppointmentID BIGINT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    `Date` DATE NOT NULL,
    `Time` TIME NOT NULL,
    `Status` VARCHAR(255) NOT NULL,
    PatientID BIGINT NOT NULL UNIQUE,
    DoctorID BIGINT NOT NULL UNIQUE,
    Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PatientID) REFERENCES Patients(PatientID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID) ON DELETE RESTRICT ON UPDATE CASCADE
);




INSERT INTO Appointments (`Date`, `Time`, PatientID, DoctorID) VALUES 
('2024-12-20', '09:00:00', 1, 1), 
('2024-12-20', '10:00:00', 2, 2), 
('2024-12-20', '11:00:00', 3, 3), 
('2024-12-21', '09:30:00', 4, 4), 
('2024-12-21', '10:30:00', 5, 5);
